export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const INTRO_SCREEN = 'INTRO_SCREEN';
export const ORDER_SCREEN = 'ORDER_SCREEN';
export const CREATE_ORDER_SCREEN = 'CREATE_ORDER_SCREEN';
